server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100 # in query 자동 작성
  output:
    ansi:
      enabled: always
  security:
    user:
      name: ssar
      password: 1234

logging:
  level:
    '[shop.donutmarket.donut]': DEBUG # DEBUG 레벨부터 에러 확인할 수 있게 설정하기
    '[org.hibernate.orm.jdbc.bind]': TRACE # 콘솔 쿼리에 ? 에 주입된 값 보기

meta:
  name: ${HS512_SECRET} # _대신 .을 쓸 수도 있다.

sentry:
  dsn: ${SENTRY}
  traces-sample-rate: 1.0
  logging:
    minimum-event-level: info

boot-pay:
  rest-api-key: ${REST_API_KEY}
  private-key: ${PRIVATE_KEY}



